StateCodelab/build.gradle
StateCodelab/finished/build.gradle
StateCodelab/finished/src/main/java/com/codelabs/state/todo/TodoActivity.kt
StateCodelab/finished/src/main/java/com/codelabs/state/todo/TodoComponents.kt
StateCodelab/finished/src/main/java/com/codelabs/state/todo/TodoScreen.kt
StateCodelab/start/build.gradle
StateCodelab/start/src/main/java/com/codelabs/state/examples/ExpandingCard.kt
StateCodelab/start/src/main/java/com/codelabs/state/examples/HelloCodelabActivity.kt
StateCodelab/start/src/main/java/com/codelabs/state/todo/TodoActivity.kt
StateCodelab/start/src/main/java/com/codelabs/state/todo/TodoComponents.kt

Changes:
- Migrate from Stack to Box
- Change imports for Box
- Restructure code for slot to use Box(modifier) { slot() } to workaround compiler bug
- Also extracted ExpandingCard.kt standalone UDF example to a separate file.

Bump StateCodelab to Alpha04

---

StateCodelab/build.gradle
StateCodelab/finished/src/main/java/com/codelabs/state/todo/TodoScreen.kt

Text should be republished when merged.

[State] Bump State codelab to alpha05. 

---

BasicsCodelab/app/src/main/java/com/codelab/basics/MainActivity.kt
BasicsCodelab/build.gradle
BasicsCodelab/gradle/wrapper/gradle-wrapper.properties

#35 was merged into the wrong branch

Revert "Update Basics codelab to Compose 6922857 snapshot"

---

StateCodelab/build.gradle
StateCodelab/finished/src/main/java/com/codelabs/state/todo/TodoComponents.kt
StateCodelab/finished/src/main/java/com/codelabs/state/todo/TodoScreen.kt
StateCodelab/start/src/main/java/com/codelabs/state/todo/TodoComponents.kt
StateCodelab/start/src/main/java/com/codelabs/state/todo/TodoScreen.kt

ImeActions are working in this alpha release!

[State] Bump state codelab to alpha 07

---

BasicsCodelab/README.md
LayoutsCodelab/README.md
MigrationCodelab/README.md
README.md
StateCodelab/README.md
ThemingCodelab/README.md

@yrezgui I'm reopening the PR as #58 was closed

Fix links to codelabs in internal README files

---

ThemingCodelab/build.gradle

Reverts googlecodelabs/android-compose-codelabs#79

Revert "[Theming] Update to snapshot 7067732."

---

ThemingCodelab/build.gradle

Change-Id: I85b9a95f77c30fdd7b721f3bb9803355573f37be

[Theming] Update to snapshot 7067732.

---

BasicsCodelab/app/src/main/java/com/codelab/basics/MainActivity.kt
BasicsCodelab/build.gradle

Added list & animation section

[Basics] updates to alpha10 release

---

ThemingCodelab/app/src/main/java/com/codelab/theming/ui/finish/Home.kt
ThemingCodelab/app/src/main/java/com/codelab/theming/ui/start/Home.kt
ThemingCodelab/build.gradle

Also update to snapshot 7154166 & AGP alpha07

[Theming] Mark headers for a11y.

---

AnimationCodelab/start/src/main/java/com/example/android/codelab/animation/ui/home/Home.kt

[Animation] Add PreviewHomeTab to start/.../Home.kt

---

AnimationCodelab/build.gradle
AnimationCodelab/finished/build.gradle
AnimationCodelab/start/build.gradle
BasicsCodelab/app/build.gradle
BasicsCodelab/build.gradle
LayoutsCodelab/app/build.gradle
LayoutsCodelab/app/src/main/java/com/codelab/layouts/Lists.kt
LayoutsCodelab/build.gradle
MigrationCodelab/app/build.gradle
MigrationCodelab/build.gradle
StateCodelab/build.gradle
StateCodelab/finished/build.gradle
StateCodelab/start/build.gradle
ThemingCodelab/app/build.gradle
ThemingCodelab/app/src/main/java/com/codelab/theming/ui/finish/theme/Theme.kt
ThemingCodelab/build.gradle

Checks passed on #141 , merging this CL optimistically

[All main] Update to beta03

---

MigrationCodelab/app/build.gradle
MigrationCodelab/build.gradle

Checks passed on #142 , merging this CL optimistically

[Migration end] Update to beta03

---

AnimationCodelab/build.gradle
AnimationCodelab/finished/build.gradle
AnimationCodelab/start/build.gradle
AnimationCodelab/start/src/main/java/com/example/android/codelab/animation/ui/home/Home.kt

Fixes #166
Fixes #145
Fixes #174

[Animation] Update the start module

---

NavigationCodelab/app/build.gradle

Removed duplicate Material Compose dependency.

Removed duplicate dependency

---

.github/workflows/AccessibilityCodelab.yaml
.github/workflows/NavigationCodelab.yaml
.github/workflows/TestingCodelab.yaml

(This is not enough to make end build though, see next PR)

Adds end branch to CI

---

.github/workflows/NavigationCodelab.yaml
.github/workflows/TestingCodelab.yaml

Workflow files must exist in the PR commit, so they need to be duplicated in main and end.
TODO: This is to enable triggering actions, but we need to investigate which files are actually read.

[end] Adds end branch to CI

---

AccessibilityCodelab/app/src/main/java/com/example/jetnews/ui/home/PostCards.kt

Fixes #317. Codelab text has already been updated.

[End] Re-use showFewerLabel. 

---

README.md

Adaptive codelab is part of core compose codelabs, so it's good to add it to readme for easier access and information.

Added adaptive codelab in Readme

---

MigrationCodelab/app/build.gradle
MigrationCodelab/app/src/main/java/com/google/samples/apps/sunflower/plantdetail/PlantDetailDescription.kt
MigrationCodelab/app/src/main/java/com/google/samples/apps/sunflower/plantdetail/PlantDetailFragment.kt
MigrationCodelab/app/src/main/java/com/google/samples/apps/sunflower/theme/Theme.kt

Using a `MaterialTheme` directly over `MdcTheme`

Update solution code for Migration Codelab

---

MigrationCodelab/app/build.gradle
MigrationCodelab/app/src/main/java/com/google/samples/apps/sunflower/theme/Theme.kt

- Remove theme adapter from dependencies.
- Add Theme.kt

Update starter code for Migration Codelab

---

MigrationCodelab/app/src/androidTest/java/com/google/samples/apps/sunflower/viewmodels/PlantDetailViewModelTest.kt
MigrationCodelab/app/src/main/java/com/google/samples/apps/sunflower/data/GardenPlantingRepository.kt
MigrationCodelab/app/src/main/java/com/google/samples/apps/sunflower/utilities/InjectorUtils.kt
MigrationCodelab/app/src/main/java/com/google/samples/apps/sunflower/viewmodels/PlantDetailViewModel.kt

Run DAO operation on Dispatchers.IO (main)

---

AdaptiveUiCodelab/app/build.gradle.kts
AdaptiveUiCodelab/app/src/main/java/com/example/reply/ui/ReplyApp.kt
AdaptiveUiCodelab/app/src/main/java/com/example/reply/ui/ReplyNavigation.kt
AdaptiveUiCodelab/app/src/main/res/values/strings.xml
AdaptiveUiCodelab/gradle/libs.versions.toml

Note this component doesn't support a navigation drawer. Keeping `NavigationDrawerContent` composable for now in case we intend to implement support for showing the drawer again.

[AdaptiveUiCodelab] Use NavigationSuiteScaffold

---

NavigationCodelab/app/src/main/java/com/example/compose/rally/RallyDestinations.kt

Refines it to a sealed interface for precise intent.

Seal RallyDestination

---

AccessibilityCodelab/.gitignore
AdaptiveUiCodelab/.gitignore
AdvancedStateAndSideEffectsCodelab/.gitignore
BasicLayoutsCodelab/.gitignore
MigrationCodelab/.gitignore
NavigationCodelab/.gitignore
PerformanceCodelab/.gitignore
TestingCodelab/.gitignore
ThemingCodelab/.gitignore

https://kotlinlang.org/docs/whatsnew20.html#new-directory-for-kotlin-data-in-gradle-projects

[MAIN] Gitignore .kotlin folder

---

.gitignore
AccessibilityCodelab/.gitignore
AdaptiveUiCodelab/.gitignore
AdvancedStateAndSideEffectsCodelab/.gitignore
BasicLayoutsCodelab/.gitignore
MigrationCodelab/.gitignore
NavigationCodelab/.gitignore
PerformanceCodelab/.gitignore
TestingCodelab/.gitignore
ThemingCodelab/.gitignore

https://kotlinlang.org/docs/whatsnew20.html#new-directory-for-kotlin-data-in-gradle-projects

[END] Gitignore the .kotlin folders

---

AnimationCodelab/README.md

The AnimationCodelab README had a dead link.

Update codelabs link in the README.md

---

NavigationCodelab/app/src/main/java/com/example/compose/rally/RallyActivity.kt

Fix default Accounts destination - temporary fix until type safe args are added to this codelab and we can use the new hasRoute API

Fix default Accounts destination

---

.github/workflows/AccessibilityCodelab.yaml
.github/workflows/AdvancedStateAndSideEffectsCodelab.yaml
.github/workflows/AnimationCodelab.yaml
.github/workflows/BasicLayoutsCodelab.yaml
.github/workflows/BasicStateCodelab.yaml
.github/workflows/BasicsCodelab.yaml
.github/workflows/MigrationCodelab.yaml
.github/workflows/NavigationCodelab.yaml
.github/workflows/TestingCodelab.yaml
.github/workflows/ThemingCodelab.yaml

This PR standardizes GitHub Actions triggers in workflow files within `.github/workflows/`.
The goal is to ensure workflows run consistently on `push`, `pull_request`, and `workflow_dispatch` events where appropriate.
This is part of a batch of pull requests across repositories owned by the `android` organization on GitHub.
**Project Owner:** Please review the changes carefully to ensure they are correct and appropriate for this project before approving and merging.
* If you do not think this change is appropriate (e.g., a workflow should NOT run on one of these triggers), please leave a comment explaining why.
* If you think the goal is appropriate but notice a mistake in the implementation, please leave a comment detailing the mistake.

Add triggers to .github/workflows/
